# Copyright 2026 The Alibaba Qwen team and Qwen3-TTS-MLX contributors.
# SPDX-License-Identifier: Apache-2.0
"""Gradio UI based on the official Qwen3-TTS demo, with an MLX backend."""

from __future__ import annotations

import gradio as gr
import numpy as np

from .audio import from_gradio
from .long_form import save_long_form_bundle, synthesize_long_form
from .manager import ModelManager
from .models import LANGUAGES, PRECISIONS, SPEAKERS, ModelKind, resolve_model
from .profiles import VoiceProfile, load_voice_profile, save_voice_profile

DISCLAIMER = """
**Disclaimer (免责声明)**

- Audio is generated by an AI model for demonstration. Do not use this service to
  create unlawful, harmful, fraudulent, privacy-infringing, or unauthorized deepfake
  content. You are responsible for evaluating and using generated audio lawfully.
- 音频由人工智能模型自动生成，仅用于体验与展示。严禁利用本服务生成违法、有害、欺诈、
  侵犯隐私或未经授权的深度伪造内容。用户应自行承担合法使用生成音频的责任。
"""

APP_CSS = """
.gradio-container {max-width: 1440px !important;}
.mlx-badge {color: #0a7; font-weight: 700;}
"""


def launch_options() -> dict:
    """Return visual options accepted by Gradio 6's launch method."""

    return {
        "theme": gr.themes.Soft(
            font=[gr.themes.GoogleFont("Source Sans Pro"), "Arial", "sans-serif"]
        ),
        "css": APP_CSS,
    }


def _audio_output(wavs: list[np.ndarray], sample_rate: int):
    return sample_rate, np.asarray(wavs[0], dtype=np.float32)


def _generation_kwargs(max_tokens, temperature, top_k, top_p, repetition_penalty):
    return {
        "max_new_tokens": int(max_tokens),
        "temperature": float(temperature),
        "top_k": int(top_k),
        "top_p": float(top_p),
        "repetition_penalty": float(repetition_penalty),
    }


def _advanced_controls():
    with gr.Accordion("Advanced generation settings (高级生成设置)", open=False):
        with gr.Row():
            max_tokens = gr.Slider(128, 4096, value=2048, step=128, label="Max tokens")
            temperature = gr.Slider(0.1, 1.5, value=0.9, step=0.05, label="Temperature")
        with gr.Row():
            top_k = gr.Slider(0, 100, value=50, step=1, label="Top-k")
            top_p = gr.Slider(0.05, 1.0, value=1.0, step=0.05, label="Top-p")
            repetition = gr.Slider(
                1.0, 2.0, value=1.05, step=0.05, label="Repetition penalty"
            )
    return max_tokens, temperature, top_k, top_p, repetition


def _model_controls(include_size: bool = True):
    with gr.Row():
        size = (
            gr.Dropdown(["1.7B", "0.6B"], value="1.7B", label="Model size")
            if include_size
            else gr.State("1.7B")
        )
        precision = gr.Dropdown(list(PRECISIONS), value="bf16", label="MLX precision")
    return size, precision


def build_demo(manager: ModelManager | None = None) -> gr.Blocks:
    """Build the full official-style experience without loading a model yet."""

    manager = manager or ModelManager()
    with gr.Blocks(title="Qwen3-TTS MLX") as demo:
        gr.Markdown(
            """
# Qwen3 TTS MLX Demo

An unofficial Apple Silicon implementation of the official Qwen3-TTS experience.
Model inference runs locally through **MLX-Audio**; checkpoints download from
`mlx-community` on first use. <span class="mlx-badge">Apple Silicon · Metal · Local</span>
"""
        )

        with gr.Tabs():
            with gr.Tab("Custom Voice (预置音色)"):
                with gr.Row():
                    with gr.Column(scale=2):
                        custom_text = gr.Textbox(
                            label="Text (待合成文本)",
                            lines=5,
                            placeholder="Enter text to synthesize (输入要合成的文本).",
                        )
                        with gr.Row():
                            custom_language = gr.Dropdown(
                                list(LANGUAGES), value="Auto", label="Language (语种)"
                            )
                            custom_speaker = gr.Dropdown(
                                list(SPEAKERS), value="Vivian", label="Speaker (说话人)"
                            )
                        custom_instruction = gr.Textbox(
                            label="Instruction (Optional) (控制指令，可不输入)",
                            lines=2,
                            placeholder="e.g. Say it in a very angry tone.",
                        )
                        custom_size, custom_precision = _model_controls()
                        custom_advanced = _advanced_controls()
                        custom_button = gr.Button("Generate (生成)", variant="primary")
                    with gr.Column(scale=3):
                        custom_audio = gr.Audio(label="Output Audio (合成结果)", type="numpy")
                        custom_status = gr.Textbox(label="Status (状态)", lines=3)

                def run_custom(
                    text, language, speaker, instruction, size, precision, *generation
                ):
                    try:
                        if not (text or "").strip():
                            return None, "Text is required (必须填写文本)."
                        spec = resolve_model(ModelKind.CUSTOM_VOICE, size, precision)
                        effective_instruction = (instruction or "").strip() or None
                        note = ""
                        if not spec.instruction_control and effective_instruction:
                            effective_instruction = None
                            note = " 0.6B does not support instruction control; instruction ignored."
                        wavs, sample_rate = manager.run(
                            ModelKind.CUSTOM_VOICE,
                            size,
                            precision,
                            "generate_custom_voice",
                            text=text.strip(),
                            language=language,
                            speaker=speaker,
                            instruct=effective_instruction,
                            **_generation_kwargs(*generation),
                        )
                        return _audio_output(wavs, sample_rate), f"Finished. `{spec.model_id}`.{note}"
                    except Exception as exc:  # noqa: BLE001 - UI boundary reports failures
                        return None, f"{type(exc).__name__}: {exc}"

                custom_button.click(
                    run_custom,
                    inputs=[
                        custom_text,
                        custom_language,
                        custom_speaker,
                        custom_instruction,
                        custom_size,
                        custom_precision,
                        *custom_advanced,
                    ],
                    outputs=[custom_audio, custom_status],
                )

            with gr.Tab("Voice Design (音色设计)"):
                with gr.Row():
                    with gr.Column(scale=2):
                        design_text = gr.Textbox(
                            label="Text (待合成文本)",
                            lines=5,
                            value=(
                                "It's in the top drawer... wait, it's empty? No way, "
                                "that's impossible! I'm sure I put it there!"
                            ),
                        )
                        design_language = gr.Dropdown(
                            list(LANGUAGES), value="Auto", label="Language (语种)"
                        )
                        design_instruction = gr.Textbox(
                            label="Voice Design Instruction (音色描述)",
                            lines=3,
                            value=(
                                "Speak in an incredulous tone, with a hint of panic "
                                "beginning to creep into the voice."
                            ),
                        )
                        design_size, design_precision = _model_controls(include_size=False)
                        design_advanced = _advanced_controls()
                        design_button = gr.Button("Generate (生成)", variant="primary")
                    with gr.Column(scale=3):
                        design_audio = gr.Audio(label="Output Audio (合成结果)", type="numpy")
                        design_status = gr.Textbox(label="Status (状态)", lines=3)

                def run_design(text, language, instruction, size, precision, *generation):
                    try:
                        if not (text or "").strip():
                            return None, "Text is required (必须填写文本)."
                        if not (instruction or "").strip():
                            return None, "Voice design instruction is required (必须填写音色描述)."
                        spec = resolve_model(ModelKind.VOICE_DESIGN, size, precision)
                        wavs, sample_rate = manager.run(
                            ModelKind.VOICE_DESIGN,
                            size,
                            precision,
                            "generate_voice_design",
                            text=text.strip(),
                            language=language,
                            instruct=instruction.strip(),
                            **_generation_kwargs(*generation),
                        )
                        return _audio_output(wavs, sample_rate), f"Finished. `{spec.model_id}`."
                    except Exception as exc:  # noqa: BLE001 - UI boundary reports failures
                        return None, f"{type(exc).__name__}: {exc}"

                design_button.click(
                    run_design,
                    inputs=[
                        design_text,
                        design_language,
                        design_instruction,
                        design_size,
                        design_precision,
                        *design_advanced,
                    ],
                    outputs=[design_audio, design_status],
                )

            with gr.Tab("Voice Clone (声音复刻)"):  # noqa: SIM117 - clearer Gradio tree
                with gr.Tabs():
                    with gr.Tab("Clone & Generate (克隆并合成)"):
                        with gr.Row():
                            with gr.Column(scale=2):
                                clone_reference = gr.Audio(
                                    label="Reference Audio (参考音频)", type="numpy"
                                )
                                clone_ref_text = gr.Textbox(
                                    label="Reference Text (参考音频文本)", lines=3
                                )
                                clone_xvector = gr.Checkbox(
                                    label=(
                                        "Use x-vector only (无需参考文本，但相似度可能降低)"
                                    ),
                                    value=False,
                                )
                            with gr.Column(scale=2):
                                clone_text = gr.Textbox(
                                    label="Target Text (待合成文本)", lines=5
                                )
                                clone_language = gr.Dropdown(
                                    list(LANGUAGES), value="Auto", label="Language (语种)"
                                )
                                clone_size, clone_precision = _model_controls()
                                clone_advanced = _advanced_controls()
                                clone_button = gr.Button("Generate (生成)", variant="primary")
                            with gr.Column(scale=3):
                                clone_audio = gr.Audio(
                                    label="Output Audio (合成结果)", type="numpy"
                                )
                                clone_status = gr.Textbox(label="Status (状态)", lines=3)

                        def run_clone(
                            reference,
                            ref_text,
                            xvector,
                            text,
                            language,
                            size,
                            precision,
                            *generation,
                        ):
                            try:
                                audio = from_gradio(reference)
                                if audio is None:
                                    return None, "Reference audio is required (必须上传参考音频)."
                                if not (text or "").strip():
                                    return None, "Target text is required (必须填写待合成文本)."
                                if not xvector and not (ref_text or "").strip():
                                    return None, (
                                        "Reference text is required unless x-vector-only mode is enabled."
                                    )
                                spec = resolve_model(ModelKind.BASE, size, precision)
                                wavs, sample_rate = manager.run(
                                    ModelKind.BASE,
                                    size,
                                    precision,
                                    "generate_voice_clone",
                                    text=text.strip(),
                                    language=language,
                                    ref_audio=audio,
                                    ref_text=(ref_text or "").strip() or None,
                                    x_vector_only_mode=bool(xvector),
                                    **_generation_kwargs(*generation),
                                )
                                penalty_note = ""
                                if not xvector and float(generation[-1]) < 1.5:
                                    penalty_note = (
                                        " MLX-Audio applies a minimum 1.5 repetition penalty "
                                        "for transcript cloning."
                                    )
                                return _audio_output(wavs, sample_rate), (
                                    f"Finished. `{spec.model_id}`.{penalty_note}"
                                )
                            except Exception as exc:  # noqa: BLE001 - UI boundary reports failures
                                return None, f"{type(exc).__name__}: {exc}"

                        clone_button.click(
                            run_clone,
                            inputs=[
                                clone_reference,
                                clone_ref_text,
                                clone_xvector,
                                clone_text,
                                clone_language,
                                clone_size,
                                clone_precision,
                                *clone_advanced,
                            ],
                            outputs=[clone_audio, clone_status],
                        )

                    with gr.Tab("Save / Load Voice (保存/加载克隆音色)"):
                        with gr.Row():
                            with gr.Column(scale=2):
                                gr.Markdown(
                                    "### Save Voice\nStore reference audio and text as a safe `.qvoice` profile."
                                )
                                save_reference = gr.Audio(
                                    label="Reference Audio (参考音频)", type="numpy"
                                )
                                save_ref_text = gr.Textbox(
                                    label="Reference Text (参考音频文本)", lines=3
                                )
                                save_xvector = gr.Checkbox(
                                    label="Use x-vector only (仅用说话人向量)", value=False
                                )
                                save_button = gr.Button("Save Voice File", variant="primary")
                                saved_file = gr.File(label="Voice File (.qvoice)")
                                save_status = gr.Textbox(label="Status (状态)")
                            with gr.Column(scale=2):
                                gr.Markdown(
                                    "### Load Voice & Generate\nLoad a `.qvoice` profile and synthesize new text."
                                )
                                profile_file = gr.File(
                                    label="Upload Voice File", file_types=[".qvoice", ".zip"]
                                )
                                profile_text = gr.Textbox(
                                    label="Target Text (待合成文本)", lines=5
                                )
                                profile_language = gr.Dropdown(
                                    list(LANGUAGES), value="Auto", label="Language (语种)"
                                )
                                profile_size, profile_precision = _model_controls()
                                profile_advanced = _advanced_controls()
                                profile_button = gr.Button("Generate (生成)", variant="primary")
                            with gr.Column(scale=3):
                                profile_audio = gr.Audio(
                                    label="Output Audio (合成结果)", type="numpy"
                                )
                                profile_status = gr.Textbox(label="Status (状态)", lines=3)

                        def save_profile(reference, ref_text, xvector):
                            try:
                                audio = from_gradio(reference)
                                if audio is None:
                                    return None, "Reference audio is required."
                                waveform, sample_rate = audio
                                path = save_voice_profile(
                                    VoiceProfile(
                                        audio=waveform,
                                        sample_rate=sample_rate,
                                        ref_text=(ref_text or "").strip() or None,
                                        x_vector_only=bool(xvector),
                                    )
                                )
                                return path, "Finished. Portable .qvoice profile created."
                            except Exception as exc:  # noqa: BLE001 - UI boundary reports failures
                                return None, f"{type(exc).__name__}: {exc}"

                        def run_profile(
                            profile_file_value,
                            text,
                            language,
                            size,
                            precision,
                            *generation,
                        ):
                            try:
                                if profile_file_value is None:
                                    return None, "Voice file is required."
                                if not (text or "").strip():
                                    return None, "Target text is required."
                                profile = load_voice_profile(profile_file_value)
                                spec = resolve_model(ModelKind.BASE, size, precision)
                                wavs, sample_rate = manager.run(
                                    ModelKind.BASE,
                                    size,
                                    precision,
                                    "generate_voice_clone",
                                    text=text.strip(),
                                    language=language,
                                    ref_audio=profile.audio_tuple,
                                    ref_text=profile.ref_text,
                                    x_vector_only_mode=profile.x_vector_only,
                                    **_generation_kwargs(*generation),
                                )
                                return _audio_output(wavs, sample_rate), (
                                    f"Finished. `{spec.model_id}`."
                                )
                            except Exception as exc:  # noqa: BLE001 - UI boundary reports failures
                                return None, f"{type(exc).__name__}: {exc}"

                        save_button.click(
                            save_profile,
                            inputs=[save_reference, save_ref_text, save_xvector],
                            outputs=[saved_file, save_status],
                        )
                        profile_button.click(
                            run_profile,
                            inputs=[
                                profile_file,
                                profile_text,
                                profile_language,
                                profile_size,
                                profile_precision,
                                *profile_advanced,
                            ],
                            outputs=[profile_audio, profile_status],
                        )

                    with gr.Tab("Design → Clone (设计音色并复刻)"):
                        gr.Markdown(
                            "Design a reference voice with VoiceDesign, then use the Base "
                            "model to speak new text in that voice. Two checkpoints are loaded "
                            "sequentially to keep unified-memory use bounded."
                        )
                        with gr.Row():
                            with gr.Column(scale=2):
                                bridge_reference_text = gr.Textbox(
                                    label="Reference Text (参考音频文本)",
                                    lines=3,
                                    value="Hello! This sample defines the voice we will reuse.",
                                )
                                bridge_instruction = gr.Textbox(
                                    label="Voice Design Instruction (音色描述)",
                                    lines=3,
                                    value=(
                                        "A warm, calm adult voice with clear pronunciation and "
                                        "a natural conversational pace."
                                    ),
                                )
                                bridge_reference_audio = gr.Audio(
                                    label="Designed Reference (设计的参考音频)", type="numpy"
                                )
                                bridge_design_button = gr.Button(
                                    "1. Design Reference Voice (设计参考音色)", variant="secondary"
                                )
                            with gr.Column(scale=2):
                                bridge_target_text = gr.Textbox(
                                    label="Target Text (待合成文本)", lines=5
                                )
                                bridge_language = gr.Dropdown(
                                    list(LANGUAGES), value="Auto", label="Language (语种)"
                                )
                                bridge_size, bridge_precision = _model_controls()
                                bridge_advanced = _advanced_controls()
                                bridge_clone_button = gr.Button(
                                    "2. Generate with Reference (使用参考音色生成)",
                                    variant="primary",
                                )
                            with gr.Column(scale=3):
                                bridge_audio = gr.Audio(
                                    label="Cloned Output (复刻合成结果)", type="numpy"
                                )
                                bridge_status = gr.Textbox(label="Status (状态)", lines=4)

                        def run_design_reference(
                            reference_text,
                            instruction,
                            language,
                            precision,
                            *generation,
                        ):
                            try:
                                if not (reference_text or "").strip():
                                    return None, "Reference text is required."
                                if not (instruction or "").strip():
                                    return None, "Voice design instruction is required."

                                kwargs = _generation_kwargs(*generation)
                                design_spec = resolve_model(
                                    ModelKind.VOICE_DESIGN, "1.7B", precision
                                )
                                reference_wavs, reference_rate = manager.run(
                                    ModelKind.VOICE_DESIGN,
                                    "1.7B",
                                    precision,
                                    "generate_voice_design",
                                    text=reference_text.strip(),
                                    language=language,
                                    instruct=instruction.strip(),
                                    **kwargs,
                                )
                                return _audio_output(reference_wavs, reference_rate), (
                                    f"Reference ready. `{design_spec.model_id}`. "
                                    "You can reuse it for multiple target texts."
                                )
                            except Exception as exc:  # noqa: BLE001 - UI boundary reports failures
                                return None, f"{type(exc).__name__}: {exc}"

                        def run_designed_clone(
                            reference,
                            reference_text,
                            target_text,
                            language,
                            size,
                            precision,
                            *generation,
                        ):
                            try:
                                audio = from_gradio(reference)
                                if audio is None:
                                    return None, "Create or upload a designed reference first."
                                if not (reference_text or "").strip():
                                    return None, "Reference text is required."
                                if not (target_text or "").strip():
                                    return None, "Target text is required."
                                kwargs = _generation_kwargs(*generation)
                                base_spec = resolve_model(ModelKind.BASE, size, precision)
                                output_wavs, output_rate = manager.run(
                                    ModelKind.BASE,
                                    size,
                                    precision,
                                    "generate_voice_clone",
                                    text=target_text.strip(),
                                    language=language,
                                    ref_audio=audio,
                                    ref_text=reference_text.strip(),
                                    x_vector_only_mode=False,
                                    **kwargs,
                                )
                                return _audio_output(output_wavs, output_rate), (
                                    f"Finished with the reusable reference. `{base_spec.model_id}`."
                                )
                            except Exception as exc:  # noqa: BLE001 - UI boundary reports failures
                                return None, f"{type(exc).__name__}: {exc}"

                        bridge_design_button.click(
                            run_design_reference,
                            inputs=[
                                bridge_reference_text,
                                bridge_instruction,
                                bridge_language,
                                bridge_precision,
                                *bridge_advanced,
                            ],
                            outputs=[bridge_reference_audio, bridge_status],
                        )
                        bridge_clone_button.click(
                            run_designed_clone,
                            inputs=[
                                bridge_reference_audio,
                                bridge_reference_text,
                                bridge_target_text,
                                bridge_language,
                                bridge_size,
                                bridge_precision,
                                *bridge_advanced,
                            ],
                            outputs=[bridge_audio, bridge_status],
                        )

            with gr.Tab("Long Form (장문 제작)"):
                gr.Markdown(
                    "Split long text at paragraph and sentence boundaries, synthesize each "
                    "section, and download both the combined audio and a ZIP with every section. "
                    "For the most consistent character voice, use **Voice Clone**."
                )
                with gr.Row():
                    with gr.Column(scale=3):
                        long_text = gr.Textbox(
                            label="Long Text (장문 원고)",
                            lines=14,
                            placeholder="Paste multiple paragraphs here (여러 문단을 붙여 넣으세요).",
                        )
                        long_workflow = gr.Dropdown(
                            ["Custom Voice", "Voice Design", "Voice Clone"],
                            value="Custom Voice",
                            label="Workflow (생성 방식)",
                        )
                        with gr.Row():
                            long_language = gr.Dropdown(
                                list(LANGUAGES), value="Auto", label="Language (语种)"
                            )
                            long_speaker = gr.Dropdown(
                                list(SPEAKERS), value="Sohee", label="Speaker (说话人)"
                            )
                        long_instruction = gr.Textbox(
                            label="Instruction / Voice Description",
                            lines=3,
                            placeholder=(
                                "Optional for Custom Voice; required for Voice Design."
                            ),
                        )
                        long_reference = gr.Audio(
                            label="Reference Audio (Voice Clone only)", type="numpy"
                        )
                        long_ref_text = gr.Textbox(
                            label="Reference Text (Voice Clone only)", lines=3
                        )
                        long_xvector = gr.Checkbox(
                            label="Use x-vector only (Voice Clone)", value=False
                        )
                    with gr.Column(scale=2):
                        long_size, long_precision = _model_controls()
                        with gr.Row():
                            long_max_chars = gr.Slider(
                                80,
                                1000,
                                value=500,
                                step=20,
                                label="Maximum characters per section",
                            )
                            long_pause = gr.Slider(
                                0,
                                2000,
                                value=650,
                                step=50,
                                label="Pause between sections (ms)",
                            )
                        long_advanced = _advanced_controls()
                        long_button = gr.Button("Generate Long Form (장문 생성)", variant="primary")
                    with gr.Column(scale=3):
                        long_audio = gr.Audio(label="Combined Audio (합본)", type="numpy")
                        long_bundle = gr.File(label="Sections + Manifest (.zip)")
                        long_status = gr.Textbox(label="Status (상태)", lines=4)

                def run_long_form(
                    text,
                    workflow,
                    language,
                    speaker,
                    instruction,
                    reference,
                    ref_text,
                    xvector,
                    size,
                    precision,
                    max_chars,
                    pause_ms,
                    *generation,
                ):
                    try:
                        if not (text or "").strip():
                            return None, None, "Long-form text is required."
                        kwargs = _generation_kwargs(*generation)
                        note = ""

                        if workflow == "Custom Voice":
                            spec = resolve_model(ModelKind.CUSTOM_VOICE, size, precision)

                            def generate(section):
                                return manager.run(
                                    ModelKind.CUSTOM_VOICE,
                                    size,
                                    precision,
                                    "generate_custom_voice",
                                    text=section,
                                    language=language,
                                    speaker=speaker,
                                    instruct=(instruction or "").strip() or None,
                                    **kwargs,
                                )

                            if not spec.instruction_control and (instruction or "").strip():
                                note = " 0.6B ignores Custom Voice instructions."
                        elif workflow == "Voice Design":
                            if not (instruction or "").strip():
                                return None, None, "Voice Design requires a voice description."
                            spec = resolve_model(ModelKind.VOICE_DESIGN, "1.7B", precision)

                            def generate(section):
                                return manager.run(
                                    ModelKind.VOICE_DESIGN,
                                    "1.7B",
                                    precision,
                                    "generate_voice_design",
                                    text=section,
                                    language=language,
                                    instruct=instruction.strip(),
                                    **kwargs,
                                )

                        elif workflow == "Voice Clone":
                            audio = from_gradio(reference)
                            if audio is None:
                                return None, None, "Voice Clone requires reference audio."
                            if not xvector and not (ref_text or "").strip():
                                return None, None, (
                                    "Reference text is required unless x-vector-only mode is enabled."
                                )
                            spec = resolve_model(ModelKind.BASE, size, precision)
                            prompt = manager.run(
                                ModelKind.BASE,
                                size,
                                precision,
                                "create_voice_clone_prompt",
                                ref_audio=audio,
                                ref_text=(ref_text or "").strip() or None,
                                x_vector_only_mode=bool(xvector),
                            )

                            def generate(section):
                                return manager.run(
                                    ModelKind.BASE,
                                    size,
                                    precision,
                                    "generate_voice_clone",
                                    text=section,
                                    language=language,
                                    voice_clone_prompt=prompt,
                                    **kwargs,
                                )

                            if not xvector and float(generation[-1]) < 1.5:
                                note = " Transcript cloning uses MLX-Audio's minimum 1.5 repetition penalty."
                        else:
                            return None, None, f"Unknown workflow: {workflow}"

                        result = synthesize_long_form(
                            text.strip(),
                            generate,
                            max_chars=int(max_chars),
                            pause_ms=int(pause_ms),
                        )
                        bundle = save_long_form_bundle(result)
                        duration = result.audio.size / result.sample_rate
                        return (
                            (result.sample_rate, result.audio),
                            bundle,
                            (
                                f"Finished {len(result.texts)} section(s), {duration:.1f} seconds. "
                                f"`{spec.model_id}`.{note}"
                            ),
                        )
                    except Exception as exc:  # noqa: BLE001 - UI boundary reports failures
                        return None, None, f"{type(exc).__name__}: {exc}"

                long_button.click(
                    run_long_form,
                    inputs=[
                        long_text,
                        long_workflow,
                        long_language,
                        long_speaker,
                        long_instruction,
                        long_reference,
                        long_ref_text,
                        long_xvector,
                        long_size,
                        long_precision,
                        long_max_chars,
                        long_pause,
                        *long_advanced,
                    ],
                    outputs=[long_audio, long_bundle, long_status],
                )

        with gr.Row():
            unload_button = gr.Button("Unload model / Free MLX memory")
            unload_status = gr.Textbox(label="Model memory")

        def unload_model():
            previous = manager.loaded_model_id
            manager.unload()
            return f"Unloaded: {previous}" if previous else "No model was loaded."

        unload_button.click(unload_model, outputs=unload_status)
        gr.Markdown(DISCLAIMER)
        gr.Markdown(
            "Upstream: [QwenLM/Qwen3-TTS](https://github.com/QwenLM/Qwen3-TTS) · "
            "Runtime: [Blaizzy/mlx-audio](https://github.com/Blaizzy/mlx-audio) · "
            "This project is unofficial."
        )

    return demo
